const toursData = [
    // --- 1. Old Salt Caravan (Signature Tour) ---
    {
        id: 1,
        title: "Old Salt Caravan Private Immersion",
        price: "On Request",
        duration: "7 Days",
        location: "Marrakech ⇄ Sahara",
        image: "/images/1.jpeg", 
        desc: "Immerse yourself in the history and culture of Morocco as you follow the trail of the Old Salt Caravan from Marrakech through the Valley of a Thousand Kasbahs to the great sand seas of the Sahara Desert.",
        highlights: ["Telouet Kasbah", "Ait Ben Haddou", "Merzouga Desert", "Todra Gorges"],
        itinerary: [
            { 
                day: "Day 1", 
                title: "Marrakech", 
                desc: "Upon your arrival at the airport, your personal driver will greet you and transfer you to your riad in Marrakech for the night where you will have an opportunity to rest and recuperate from your travels. Depending on your time of arrival, you may wish to explore a little and your driver will be at your disposal should you need him. A local city guide can also be arranged.", 
                image: "images/salt_day1.jpeg" 
            },
            { 
                day: "Day 2", 
                title: "Marrakech to Ait Ben Haddou", 
                desc: "You and your driver will depart from your riad in Marrakech after breakfast to travel over the High Atlas Mountains via the Tizi n’Tichka path, reaching an altitude of nearly 7500 feet above sea level. There will be plenty of stops for tea and photographs as you take in the breathtaking vistas before turning off the main road onto the Old Salt Caravan Road to the salt mines and the former palace of the Glaoui family that owned them, Kasbah Telouet. From here, you will continue on to the UNESCO World Heritage site of Ait Ben Haddou. If this impressive ksar looks familiar, it is because it has starred (or at least made an appearance) in many movies and TV shows including Gladiator, Lawrence of Arabia, and Game of Thrones. You’ll have plenty of time to explore and climb to the 'bank' at the top, since this is also your resting stop for the night.", 
                image: "images/salt_day2.jpeg" 
            },
            { 
                day: "Day 3", 
                title: "Ait Ben Haddou to Agdz", 
                desc: "After breakfast, you will head towards Ouarzazate, a quiet city called the Door to the Desert and known for its film studios, before once again turning off the main tourist drag. Be on the lookout for a strange American looking gas station as you travel in the hills and see if you can guess in which horror movie you may have laid eyes on it (The words 'Eyes' and 'Hills' are a hint). You’ll continue on to the lush Draa Valley, also known as the valley of a million palm trees, and to the town of Agdz. Here, you can explore the local palmeraie and have a guided tour of of the ancient local Kasbah. The name Agdz means 'resting place' and, as the name implies, this oasis was an important stopping point of the old salt caravans. Relax and enjoy a delicious dinner at your kasbah for the night.", 
                image: "images/salt_day3.jpeg" 
            },
            { 
                day: "Day 4", 
                title: "Agdz to Merzouga", 
                desc: "After breakfast, you will follow the route again, making your way alongside the Draa Valley towards the sand sea of the Sahara. It may seem like a long day of driving, but it would be even longer if you were on a camel! Don’t worry, there will be plenty of stops along the way to stretch your legs and take photographs. In Rissani, the last town of significant size before you reach the dunes of Merzouga, you will have a chance to search for fossils. Long before the salt caravans, the Sahara was under the ocean and this is evident from the abundance of squid and snail fossils that really aren’t too hard to find. Afterwards, you will continue on the final stretch of today’s journey to Merzouga on the edge of Erg Chebbi, where you will get a real taste of what it was like on the Old Salt Caravan by transferring to your next mode of transportation — a camel. You will trek into the dunes to your Berber camp for the night. While on your camel, contemplate the fact that the caravans traveled just like that… for 52 more days! Once at your camp, climb a dune to watch the sunset and relax as the stars come out. Dinner will be served and traditional music will be played, before retiring to your tent for the night.", 
                image: "images/salt_day4.jpeg" 
            },
            { 
                day: "Day 5", 
                title: "Merzouga to Dades", 
                desc: "Today your camel guide will wake you early so that you can watch the sunrise over the dunes. After watching the sunrise, you’ll enjoy breakfast at camp and have time to prepare for you day, before taking a 4×4 transfer back to the edge of the dunes. Once you have reunited with your tour manager, you will travel to the oasis of Tinghir where you will go on a guided walk through the palmeraie and the old Mellah (Jewish neighborhood). After you’ve explored Tinghir, you will continue to Dades gorge where you will stop for the night.", 
                image: "images/salt_day5.jpeg" 
            },
            { 
                day: "Day 6", 
                title: "Dades to Marrakech", 
                desc: "Following breakfast you will depart from your hotel you will continue on through the Valley of a Thousand Kasbahs, each of which served as stops for the salt caravans, as you make your way back to Marrakech. You’ll take a slightly different route this time and visit the city of Ouarzazate. Here you will visit another former Glaoui palace — although this one was used by the Glaoui dynasty’s second tier of command — Kasbah Taourirt. After exploring this Kasbah, you will travel once again over the breathtaking High Atlas Mountains and back to your riad in Marrakech.", 
                image: "images/salt_day6.jpeg" 
            },
            { 
                day: "Day 7", 
                title: "Marrakech", 
                desc: "Departure day. If you didn’t have an opportunity to explore Marrakech on your arrival day and depending on your departure time, a local city guide can be arranged. Otherwise, your driver will take you to the airport and see you off wishing you bon voyage and au revoir until you next visit!", 
                image: "images/salt_day7.jpeg" 
            }
        ]
    },

    // --- 2. Grand Morocco Private Immersion (12 Days) ---
    {
        id: 2,
        title: "Grand Morocco Private Immersion",
        price: "On Request",
        duration: "12 Days",
        location: "Grand Loop",
        image: "/images/2.jpeg",
        desc: "We refer to this one as our BIG Morocco tour. You will visit the imperial cities, the mountains, the valleys, and the desert in this tour.",
        highlights: ["Imperial Cities", "Merzouga Desert", "Dades Valley", "Atlas Mountains"],
        itinerary: [
            { day: "Day 1", title: "Marrakech", desc: "Upon your arrival at the airport, your personal driver will greet you and transfer you to your riad in Marrakech for the night, where you will have an opportunity to rest and recuperate from your travels. Depending on your time of arrival, you may wish to explore a little and your driver will be at your disposal should you need him.", image: "images/grand_day1.jpeg" },
            { day: "Day 2", title: "Marrakech City Tour", desc: "After breakfast, your adventure will begin as you spend the day with a local city guide who will show you the sights and sounds of Marrakech. Marrakech, also called the Red City because of the pink walls of the medina, served as the capital city during the rule of the Saadian Dynasty who ruled Morocco from 1554 to 1659. Your tour will include visits to the old Ben Youssef Madrasa, El Badi Palace, the Saadian Tombs, and the beautiful Koutoubia Mosque. After you’ve visited these monuments, your guide will escort you to the souks of Marrakech to see how artisans still use traditional methods for their handicrafts today. After your tour, you will be driven outside of the medina to enjoy the tranquility of Marjorelle Garden which were created by the French painter Jacques Marjorelle over the course of 40 years. When you finished your stroll among the exotic plants and trees of the lush gardens, you will be taken back inside the medina to visit the famed square of Jemaa El F’na. This is the busiest square in all of Africa and it only comes alive after dark. Here, you will truly experience the sights, sounds, and even smells of Marrakech before returning to your Riad for the evening.", image: "images/grand_day2.jpeg" },
            { day: "Day 3", title: "Marrakech to Ait Ben Haddou", desc: "You and your driver will depart from your riad in Marrakech after breakfast to travel over the High Atlas Mountains via the Tizi n’Tichka path, reaching an altitude of nearly 7500 feet above sea level. They say that life is about the journey and not the destination and this is certainly true when you are on this road. There will be plenty of stops for tea and photographs as you take in the breathtaking vistas before arriving to the UNESCO World Heritage site of Ait Ben Haddou. If this impressive ksar looks familiar, it is because it has starred (or at least made an appearance) in many movies and TV shows including Gladiator, Lawrence of Arabia, and Game of Thrones. You’ll have plenty of time to explore, since this is also your resting stop for the night.", image: "images/grand_day3.jpeg" },
            { day: "Day 4", title: "Ait Ben Haddou to Kelaat M’Gouna", desc: "Today after breakfast, you will make a short drive into the heart of the Valley of the Roses. If the roses are in bloom, you can try your luck (and patience) picking the petals to sell at market. Even when the roses aren’t in bloom the Valley is always beautiful. Enjoy a walk in the oasis and a traditional couscous lunch before heading to your kasbah for the evening.", image: "images/grand_day4.jpeg" },
            { day: "Day 5", title: "Kelaat M’Gouna to Dades", desc: "Another day of light day of driving today! After breakfast, you’ll make your way to nearby Dades Gorge. You’ll have an opportunity to explore the area by your choice of transportation: hiking, mule trekking, or driving. Whichever method you choose, you will be immersed in the natural beauty of the valley and enjoy the hospitality of the people who live there.", image: "images/grand_day5.jpeg" },
            { day: "Day 6", title: "Dades to Merzouga", desc: "After breakfast, you will depart from you hotel in Dades Gorge and continue your journey towards the dunes of Merzouga, but not before experiencing the gorge from above and below. On your way to the dunes, you will stop in Rissani, the last sizable town before the dunes, where you will search for fossils before you complete the final stretch of the journey to one of the great sand seas of the Sahara, Erg Chebbi. Tonight, you will stay at a kasbah on the edge of the dunes enjoying a delicious dinner and maybe taking a dip in the pool before bed.", image: "images/grand_day6.jpeg" },
            { day: "Day 7", title: "Merzouga", desc: "Today you will take a 4×4 tour of Erg Chebbi, home to the highest dunes of the Sahara. You will visit a nomad family and the village of Gnawa musicians, Khamlia. Enjoy the music while you eat Berber pizza for lunch. Afterwards you will head back to the kasbah to relax and prepare for your camel trek. Before sunset you will take your camels into the dunes to your Berber bivouac accommodations for the night. Watch the sunset and the stars come out. Dinner will be served before you retire to the warmth of your Berber tent.", image: "images/grand_day7.jpeg" },
            { day: "Day 8", title: "Merzouga to Midelt", desc: "Today your camel guide will wake you before dawn so that you can watch the sunrise over the giant dunes. Afterwards, you will once again take to your ship of the desert (i.e. your camel) and trek back to the kasbah on the edge of the sand sea where breakfast will be served and you will have an opportunity to shower and prepare for the day. After breakfast and showers, you will leave the desert and return to the mountains as you travel along the Ziz Valley Gorge to Midelt which is located in between the High Atlas and Middle Atlas Mountains and will be your stop for the night.", image: "images/grand_day8.jpeg" },
            { day: "Day 9", title: "Midelt to Fes", desc: "After breakfast you will continue in the Middle Atlas Mountains passing through the lush cedar groves of Morocco, home of the Atlas monkeys (aka Barbary Apes). You may have seen one or two of these monkeys in Jemaa El F’na, but now you will get to a chance to see them in their natural habitat before continuing the rest of the way to the imperial city of Fes.", image: "images/grand_day9.jpeg" },
            { day: "Day 10", title: "Fes City Tour", desc: "No driving today! Your day will begin, as always, with breakfast after which you will explore the imperial city of Fes. This ancient city was actually originally two separate ones. The first, Fas Elbali, was founded by Idriss I in 789 AD and the second, Al-‘Aliya was founded by his son, Idriss II, in 808 AD and under his rule this city served as his seat of power thereby replacing Oulili as the capital of Morocco. In 1070 AD, the two cities were combined and renamed to Fes. The tour will take you into the medina of Fes through Bab Boujloud (the Blue Gate), where you will discover the ancient streets and neighborhoods, as well as Al-Qarawaiyin University. Founded in 864 AD and still in operation today, it holds the Guinness World Record for being the oldest continually operated university in the world. After discovering all that the Medina has to offer, you will be taken to get a high up panoramic view of the old city before returning to your riad for the evening.", image: "images/grand_day10.jpeg" },
            { day: "Day 11", title: "Fes to Casablanca", desc: "You will start your last full day of your Grand Morocco Tour after breakfast. You will bid farewell to Fes and make your way to the Roman ruins of Volubilis. Before the Romans came, Volubilis was an Amazigh city known as Oulili (pronounced wa-lee-lee) which dates back to the 3rd century B.C. Although severely damaged by an earthquake in the 18th century and subsequently further damaged by Moulay Ismail’s architects, it is still “an exceptionally well preserved example of a large Roman colonial town on the fringes of the Empire”, according to the UNESCO World Heritage listing. After exploring the ruins, you will continue on to another imperial city: Meknes. Your visit will begin by entering the old medina through the beautiful gate of Bab Mansour, which incorporates marble pillars that were moved from the Roman ruins of Volubilis. Once inside the medina, you will visit the tomb of Sultan Moulay Ismail. It was under his ruler’s reign from 1672 to 1727 that Meknes served its time as the capital of Morocco. Next you will visit the impressive Agdal reservoir (built under the reign of Moulay Ismail) and Heri es-Souani, a former granary and stable that lay alongside the reservoir. After exploring these sites, you will have a little free time in El-Hadim Square before continuing the rest of the way to Casablanca where you will stop for the night.", image: "images/grand_day11.jpeg" },
            { day: "Day 12", title: "Casablanca", desc: "Departure day. Your driver will transfer you to the airport where he will see you off and bid you bon voyage and au revoir until your next visit!", image: "images/grand_day12.jpeg" }
        ]
    },

    // --- 3. Ultimate Morocco Private Immersion (14 Days) ---
    {
        id: 3,
        title: "Ultimate Morocco Private Immersion",
        price: "On Request",
        duration: "14 Days",
        location: "Grand Tour + Chefchaouen",
        image: "/images/11.jpeg",
        desc: "Get ready for an unforgettable journey through Morocco’s imperial cities, ancient ruins, majestic mountains, and golden dunes. This immersive tour takes you from the vibrant energy of Casablanca to the blue-hued charm of Chefchaouen.",
        highlights: ["Chefchaouen", "Fes Immersion", "Merzouga Sahara", "Essaouira"],
        itinerary: [
            { day: "Day 1", title: "Welcome to Morocco", desc: "Welcome to Morocco! Your tour manager will be awaiting your arrival at the airport in Casablanca. Once you have made your introductions, you will depart from the airport and head to the current imperial city of Morocco: Rabat. You’ll check into your accommodations for the night and then embark on a guided tour of this modern capital city. Your tour will cover the important monuments such as the Royal Palace, the Hassan Tower, the Mausoleum of Mohamed V, and the Kasbah of the Udayas. Note: If you arrive early enough, you can stop to visit the Hassan II Mosque in Casablanca on the way to Rabat. Alternatively, if you arrive too late or do not have the energy, you can do the guided tour of Rabat on the morning of Day 2.", image: "images/ultimate_day1.jpeg" },
            { day: "Day 2", title: "Rabat to Chefchaouen", desc: "This morning, after breakfast, you will depart Rabat and head north into the Rif Mountains to Chefchaouen, the magical Blue City of Morocco. This charming small city is nestled between two peaks of the Rif Mountains that resemble horns (in fact, “chaouen” is the Berber word for “horn” and explains how the city got its name). Once here, you will check into your accommodations and then re-join your tour manager for an orientation walk in the city. Once you get your bearings, you’ll be free to explore on your own. Be sure to hike to the Spanish Mosque (ask your tour manager for directions or just follow the people) in the late afternoon to watch the sun set over the city.", image: "images/ultimate_day2.jpeg" },
            { day: "Day 3", title: "Chefchaouen", desc: "Enjoy a day free to immerse yourself in the blue charm of Chefchaouen. When you need a break from wandering the blue streets, head to the main square for a delicious meal or wander over to Hotel Parador for adult beverages. Be sure to stop and see local “laundromat” near the small waterfall of Ras el Ma. Optionally, if you are looking for a little adventure, you can head about 20 minutes outside of town to a trailhead by the Akchour River. This scenic hike weaves back and forth along the river, culminating in the big waterfall of Cascade d’Akchour.", image: "images/ultimate_day3.jpeg" },
            { day: "Day 4", title: "Chefchaouen to Fes via Volubilis", desc: "After breakfast, you will depart Chefchaouen and head south towards Fes. On the way, you will stop to visit the ruins of the Roman outpost of Volubilis. Before the Romans came, Volubilis was an Amazigh city known as Oulili which dates back to the 3rd century B.C. Although severely damaged by an earthquake in the 18th century, it is still an exceptionally well preserved example of a large Roman colonial town. After a guided tour of Volubilis, you’ll head to the lessor known imperial city of Meknes. Your visit will begin by entering the old medina through the interesting gate of Bab Mansour. Once inside the medina, you will visit the tomb of Sultan Moulay Ismail. *Meknes is currently undergoing extensive restoration and most of the important sites are closed to the public. It is an interesting city with and unique history, so you can still do a guided tour there (although it will be significantly shorter than normal) OR you can opt to skip this and enjoy the morning in Chefchaouen before transferring to Fes via Volubilis.", image: "images/ultimate_day4.jpeg" },
            { day: "Day 5", title: "Fes Immersion", desc: "Today after breakfast, your local guide will meet you at your riad and together you will embark on an odyssey through this medieval city. You will begin your tour with your driver as you make your way to the Royal Palace. After this, you will walk through the old Mellah (Jewish Quartier). When you’ve finished here, you will head to one of the towers (or Borj) of the wall that surrounds the city for panoramic views of the whole medina. Next, you’ll head to a mosaic house where you will have a demonstration of the traditional pottery methods. After this, your driver will take you as far as he can towards the medina. From here, your guide will lead you through the gates of the old city where you will discover the ancient streets and neighborhoods, visit the various artisan sections (including the tanneries), and see the important historic monuments (including the tomb of Idriss II and the Al-Qarawaiyin University – the oldest continually operated university in the world).", image: "images/ultimate_day5.jpeg" },
            { day: "Day 6", title: "Fes to Merzouga", desc: "After breakfast, you will depart from Fes and head to the desert. Your first stop on the way will be the interesting, Alpine-like city of Ifraine. After a quick stop here for coffee and a snack, you’ll continue into the Middle Atlas Mountains and through the largest cedar forest in Africa which is also home to the Barbary macaques (aka Atlas monkeys). After you’ve crossed through the Middle Atlas Mountains, you’ll pass through the city of Midelt and then continue through the High Atlas Mountains via the Ziz River Gorge. After passing through the High Atlas Mountains, you will enter the desert region and the lush oasis of Erfoud. From here, you’ll make the final leg of the journey to the Merzouga, a small city located on the edge of the big dunes of Erg Chebbi. Upon your arrival, you will check into your guest house and relax.", image: "images/ultimate_day6.jpeg" },
            { day: "Day 7", title: "Desert Tour & Camel Trek", desc: "Today you will enjoy a tour of the desert region. Your first stop of the day will be to visit the village of Khamlia which is inhabited by Gnaoua musicians. After this visit, you will head to the nearby city of Rissani. On market days this sleepy city is transformed into a bustling metropolis. After this, you’ll head to Erfoud to visit a small museum with an impressive collection of fossils found in Morocco. Then, you’ll have a chance to go search for fossils in the wild. When you have finished your tour of the area, you will head to the edge of the dunes where you will transfer to your next mode of transportation, a camel. You will begin your camel trek into the dunes to your luxury Berber camp for the night. Dinner will be served at camp followed by traditional music.", image: "images/ultimate_day7.jpeg" },
            { day: "Day 8", title: "Merzouga to Dades Valley", desc: "This morning, you’ll want to be sure to get up early to watch the sun rise over the dunes. After this near-transcendental experience, you’ll have breakfast at camp and prepare for your day. When you are ready, you’ll take a 4×4 transfer back to the edge of the dunes. Once you reunite with your tour manager, you’ll make your way to Dades Valley. Your first stop, today, will be to visit the ancient irrigation system that once brought water to the desert from the distant Saghro Mountains. From here, you’ll head to the oasis town of Tinghir where you will have a guided walk of the palmeraie and Mellah (old Jewish area). Next, you’ll visit nearby Todgha Gorge where you will walk through the most impressive part of the canyon. After this, you’ll head to your accommodations located in the Dades Valley where you will enjoy dinner at your hotel.", image: "images/ultimate_day8.jpeg" },
            { day: "Day 9", title: "Valley of Roses", desc: "Today is all about exploring how the locals live in this magical place where time seems to run slow and fast simultaneously. After a leisurely breakfast, you’ll head to the “next valley over” in the heart of the Rose Valley. On the way, you can visit a local market and then go to the home of a local family where you can help to prepare lunch (or just relax) and then join the family for a traditional couscous lunch. After lunch (and a little relaxation), you can explore a little more of the Valley either by car or by foot before heading back to your hotel in time for dinner. This area also has tons of great hiking, so if you prefer a more active day, you can choose from several options from a short hike in the unique rock formation known as the Monkey Fingers to a full-day hike through the Dades Canyon.", image: "images/ultimate_day9.jpeg" },
            { day: "Day 10", title: "Dades to Marrakech", desc: "After breakfast this morning, you and your driver will begin the journey to Marrakech by following the Road of a Thousand Kasbahs through the heart of the Valley of Roses to Ouarzazate, the Hollywood of Morocco. If you are interested and time permits, you can have a backlot tour of one of the active film studios here before making the short drive to the UNESCO World Heritage site of Ait Ben Haddou. If this impressive ksar looks familiar, it may be because it starred (or at least served as a backdrop) for many films and TV shows. Upon your arrival here, you’ll stop first for a panoramic view of this “mud city” and then head in for a closer look. After your visit here, the adventure will continue as you cross over the High Atlas Mountains via the Tizi n’Tichka pass, reaching an altitude of nearly 7500 feet above sea level before beginning your descent to Marrakech. You will arrive to your accommodations in Marrakech by late afternoon.", image: "images/ultimate_day10.jpeg" },
            { day: "Day 11", title: "Marrakech Immersion", desc: "After breakfast, your local city guide will meet you at your riad and show you all around Marrakech. Your tour will include visits to some important monuments of the Red City such as Bahia Palace, Ben Yousef Madrassa, and/or Koutoubia Mosque. In between these sites, you’ll explore the various artisanal sections of the souks where people have practiced their crafts for centuries. Your tour will end around lunchtime, and then you will have the rest of the day free to explore on your own. Don’t forget to make your way to Jemaa el F’na in the late afternoon to one of the cafés overlooking the square to watch it come alive as the sun goes down!", image: "images/ultimate_day11.jpeg" },
            { day: "Day 12", title: "Marrakech to Essaouira", desc: "Today after breakfast, you’ll make your way to the charming seaside city of Essaouira. On the way, you’ll stop at a local argan oil cooperative to see how this precious oil is produced with the help of local goats (and if you’re lucky, you may even get to see a few of these tree-climbing goats in action). You should arrive to Essaouira right around lunchtime. If you are a seafood lover, you can head with your tour manager to the wharf and pick out your lunch from the fresh catch of the day and have it grilled Moroccan-style at a nearby restaurant. After lunch, you’ll be free to explore this charming town on your own. You can do some shopping in the relaxed medina, explore the adjacent beach (known for kite-surfing), or just sit at a café in the square and watch the world pass.", image: "images/ultimate_day12.jpeg" },
            { day: "Day 13", title: "Essaouira", desc: "Today, on your last full day in Morocco, you will have the whole day to explore on your own. Of course, as always, if you need suggestions or assistance, your tour manager will be available to you. Optionally, you can spend part of today learning to make some of the delicious meals that you have experienced on your trip. This activity begins with an odyssey through the souks to find all the fresh ingredients that you will need. After gathering everything, you’ll head to the kitchen for a hands-on cooking class. Afterward, you’ll enjoy your creations with your host and her family.", image: "images/ultimate_day13.jpeg" },
            { day: "Day 14", title: "Au Revoir", desc: "This morning, after breakfast, you will transfer to the airport of your choice (Marrakech or Casablanca). There your tour manager will bid you a fond au revoir until you next trip to Morocco!", image: "images/ultimate_day14.jpeg" }
        ]
    },

    // --- 4. Complete Morocco Private Immersion (11 Days) ---
    {
        id: 4,
        title: "Complete Morocco Private Immersion",
        price: "On Request",
        duration: "11 Days",
        location: "Marrakech -> Casablanca",
        image: "/images/3.jpeg",
        desc: "Immerse yourself in Morocco’s rich culture and diverse landscapes on this 11-day journey. From the buzzing souks of Marrakech to the tranquility of the Sahara, you’ll explore ancient medinas, sleep under the stars, and connect with local traditions.",
        highlights: ["Marrakech", "Sahara Desert", "Fes", "Chefchaouen"],
        itinerary: [
            { day: "Day 1", title: "Welcome to Morocco", desc: "Welcome to Morocco! Your tour manager will be awaiting your arrival at the airport in Marrakech (or Casablanca). Once you have made your introductions, you will be transferred to your riad accommodations for the night. Once you’ve checked in, you will have the remainder of the day free to relax and/or explore on your own. Your tour manager will be available to you should you need any suggestions or assistance.", image: "images/complete_day1.jpeg" },
            { day: "Day 2", title: "Marrakech Immersion", desc: "After breakfast, your local city guide will meet you at your riad and show you all around Marrakech. Your tour will include visits to some important monuments of the Red City such as Bahia Palace, Ben Yousef Madrassa, and/or Koutoubia Mosque. In between these sites, you’ll explore the various artisanal sections of the souks where people have practiced their crafts for centuries. Your tour will end around lunchtime, and then you will have the rest of the day free to explore on your own. Don’t forget to make your way to Jemaa el F’na in the late afternoon to one of the cafés overlooking the square to watch it come alive as the sun goes down!", image: "images/complete_day2.jpeg" },
            { day: "Day 3", title: "Marrakech to Dades Valley", desc: "After breakfast this morning, you and your driver will depart from your riad in Marrakech to begin your odyssey to the Sahara Desert. Your day will start with crossing over the High Atlas Mountains via the Tizi n’Tichka path, reaching an altitude of nearly 7500 feet above sea level. There will be plenty of stops for tea and photographs as you take in the breathtaking vistas before descending to the UNESCO World Heritage Site of Ait Ben Haddou. If this impressive ksar looks familiar, it may be because it starred (or at least served as a backdrop) for many films and TV shows. After visiting here, you go through the nearby city of Ouarzazate, known as both the “Door of the Desert” and the “Holloywood of Morocco.” If you are interested and time permits, you can have a backlot tour of one of the active film studios here before continuing down the Road of a Thousand Kasbahs into the breathtaking Dades Valley where you will stop for the night.", image: "images/complete_day3.jpeg" },
            { day: "Day 4", title: "Valley of Roses", desc: "Today is all about exploring how the locals live in this magical place where time seems to run slow and fast simultaneously. After a leisurely breakfast, you’ll head to the “next valley over” in the heart of the Rose Valley. On the way, you can visit a local market and then go to the home of a local family where you can help to prepare lunch (or just relax) and then join the family for a traditional couscous lunch. After lunch (and a little relaxation), you can explore a little more of the Valley either by car or by foot before heading back to your hotel in time for dinner. This area also has tons of great hiking, so if you prefer a more active day, you can choose from several options from a short hike in the unique rock formation known as the Monkey Fingers to a full-day hike through the Dades Canyon.", image: "images/complete_day4.jpeg" },
            { day: "Day 5", title: "Dades to Merzouga", desc: "After breakfast, you will depart your accommodations in Dades and continue your journey towards the dunes of Merzouga. Your first stop on today’s journel will be the oasis city of Tinghir. You’ll enjoy a guided walk in the palmeraie here before transferring to nearby Todgha Gorge where you will have an opportunity to walk through the most impressive part of the canyon. In this narrow section of the gorge (as little as 33 feet wide), the rock walls climb straight up 525 feet on either side. After you’ve stretched your legs, you will make continue your journey into the desert region where you will have a chance to search for fossils in the wild and visit a small fossil museum with an impressive collection of specimens found in Morocco. From here, you will complete the final leg of the journey to the big dunes of Erg Chebbi near Merzouga. Here, you will transfer to your next mode of transportation, a camel, and begin your camel trek into the dunes to your luxury Berber camp for the night. Dinner will be served at camp followed by traditional music.", image: "images/complete_day5.jpeg" },
            { day: "Day 6", title: "Merzouga to Fes", desc: "This morning, you’ll want to wake up early to watch the sand change colors as the sun comes up (be sure to set your alarm!). Grab a cup of coffee and climb up the nearest dune to watch this spectacular show. After this nearly transcendental experience, you will have breakfast at camp and time to prepare for your day. When you are ready, you’ll take to your camels once again to the edge of the dunes where you will meet your tour manager and transfer back to a more conventional mode of transportation. Note: 4×4 transfer is available if one camel ride was enough! Once you reunite with your tour manager, you’ll begin the journey to Fes by first traveling along the Ziz Valley Gorge to Midelt. From here, you will continue through the Middle Atlas Mountains passing through the lush cedar groves of Morocco, home of the Atlas monkeys. After your visit here, you will travel through the alpine city of Ifraine, known as “Little Switzerland.” After this, you’ll make the final stretch of your journey Fes.", image: "images/complete_day6.jpeg" },
            { day: "Day 7", title: "Fes Immersion", desc: "Today after breakfast, your local guide will meet you at your riad and together you will embark on an odyssey through this medieval city. You will begin your tour with your driver as you make your way to the Royal Palace. After this, you will walk through the old Mellah (Jewish Quartier) where you will note a change in the architecture. When you’ve finished here, you will head to one of the towers (or Borj) of the wall that surrounds the city for panoramic views of the whole medina. Next, you’ll head to a mosaic house where you will have a demonstration of the traditional pottery methods utilized by Fassi artisans. After this, your driver will take you as far as he can towards the medina. From here, your guide will lead you through the gates of the old city where you will discover the ancient streets and neighborhoods, visit the various artisan sections (including the tanneries), and see the important historic monuments (including the tomb of Idriss II and the Al-Qarawaiyin University – the oldest continually operated university in the world).", image: "images/complete_day7.jpeg" },
            { day: "Day 8", title: "Fes to Chefchaouen via Volubilis", desc: "Today, after breakfast, you will bid farewell to Fes and make your way to the lessor known imperial city of Meknes. Your visit will begin by entering the old medina through the beautiful gate of Bab Mansour. Please note, that many of the monuments in Meknes are currently closed for extensive restoration. You can still make a stop here to see the city – it is an interesting place with a fascinating history but any tour here will be relatively abbreviated. If you prefer to skip this stop (in order to arrive in Chefchaouen earlier), just let you tour manager know. After you have explored Meknes, you will continue to the Roman Ruins of Volubilis where you will have a guided visit. Before the Romans came, Volubilis was an Amazigh city known as Oulili which dates back to the 3rd century B.C. From here, you will head to Morocco’s Blue Pearl, aka Chefchaouen, nestled between two peaks in the Rif Mountains. Once you have checked into your accommodations and had a little rest. Your tour manager will meet you for an orientation walk in the city.", image: "images/complete_day8.jpeg" },
            { day: "Day 9", title: "Chefchaouen", desc: "Today after breakfast, your local guide will meet you at your riad and together you will embark on an odyssey through this medieval city. You will begin your tour with your driver as you make your way to the Royal Palace. After this, you will walk through the old Mellah (Jewish Quartier) where you will note a change in the architecture. If you are interested in Jewish Heritage sites, let your local guide know as there are several points of interest in this neighborhood. When you’ve finished here, you will head to one of the towers (or Borj) of the wall that surrounds the city for panoramic views of the whole medina. Fes boasts the largest pedestrian-only old city in the world with over 9000 streets and alleyways. From this vantage point, you can really appreciate the size of the city.", image: "images/complete_day9.jpeg" },
            { day: "Day 10", title: "Chefchaouen to Rabat", desc: "After a leisurely breakfast, you will head south to the current capital city of Morocco, Rabat. Upon your arrival here, you’ll check into your accommodations and then meet your local guide to embark on a tour of this modern capital city. Your guided tour will include visits to all of the important monuments, such as the Royal Palace, the Hassan Tower, the Mohammed V Mausoleum, and the Kasbah of the Udayas. After your tour of the city, you’ll have the rest of the night to explore some on your own. Of course, as always, your tour manager will be available to you for any recommendations or suggestions.", image: "images/complete_day10.jpeg" },
            { day: "Day 11", title: "Au revoir!", desc: "This morning, after breakfast, you’ll be transferred to the airport in plenty of time for your departing flight. Here, your tour manager will bid you au revoir until you next trip to Morocco!", image: "images/complete_day11.jpeg" }
        ]
    },

    // --- 5. Highlights of Morocco Private Immersion (10 Days) ---
    {
        id: 5,
        title: "Highlights of Morocco Private Immersion",
        price: "On Request",
        duration: "10 Days",
        location: "Casablanca -> Marrakech",
        image: "/images/5.jpeg",
        desc: "The 10 Day Morocco Highlights Immersion Tour takes you to the magical blue city of Chefchaouen, into the bustling Imperial Cites (Rabat, Marrakech, Meknes, & Fes), through the golden sands of the Sahara, and over the Middle and High Atlas Mountains. This tour is packed with the country’s most important landmarks.",
        highlights: ["Rabat", "Chefchaouen", "Fes", "Sahara", "Marrakech"],
        itinerary: [
            { day: "Day 1", title: "Welcome to Morocco", desc: "Welcome to Morocco! Your tour manager will be awaiting your arrival at the airport in Casablanca. Once you have made your introductions, you will depart from the airport and head to the current imperial city of Morocco: Rabat. You’ll check into your accommodations for the night and then embark on a guided tour of this modern capital city. Your tour will cover the important monuments such as the Royal Palace, the Hassan Tower, the Mausoleum of Mohamed V, and the Kasbah of the Udayas.", image: "images/highlights_day1.jpeg" },
            { day: "Day 2", title: "Rabat to Chefchaouen", desc: "This morning, after breakfast, you will depart Rabat and head north into the Rif Mountains to Chefchaouen, the magical Blue City of Morocco. This charming small city is nestled between two peaks of the Rif Mountains that resemble horns (in fact, “chaouen” is the Berber word for “horn” and explains how the city got its name). Once here, you will check into your accommodations and then re-join your tour manager for an orientation walk in the city. Once you get your bearings, you’ll be free to explore on your own. Be sure to hike to the Spanish Mosque in the late afternoon to watch the sun set over the city.", image: "images/highlights_day2.jpeg" },
            { day: "Day 3", title: "Chefchaouen to Fes via Volubilis", desc: "After breakfast today, you’ll say farewell to Chefchaouen and begin your journey to Fes, the first imperial city of Morocco and the spiritual capital of the country. On the way, you will stop to visit the ruins of the Roman outpost of Volubilis. Before the Romans came, Volubilis was an Amazigh city known as Oulili which dates back to the 3rd century B.C. After a guided tour of Volubilis, you’ll head to the lessor known imperial city of Meknes. Your visit will begin by entering the old medina through the interesting gate of Bab Mansour. Note: Most of the monuments in Meknes are currently undergoing extensive restoration and are closed for the foreseeable future. You may choose to skip this stop to have more time in Chefchaouen or Fes, if you wish.", image: "images/highlights_day3.jpeg" },
            { day: "Day 4", title: "Fes Immersion", desc: "Today after breakfast, your local guide will meet you at your riad and together you will embark on an odyssey through this medieval city. You will begin your tour with your driver as you make your way to the Royal Palace. After this, you will walk through the old Mellah (Jewish Quartier) where you will note a change in the architecture. When you’ve finished here, you will head to one of the towers (or Borj) of the wall that surrounds the city for panoramic views of the whole medina. Next, you’ll head to a mosaic house where you will have a demonstration of the traditional pottery methods utilized by Fassi artisans. From here, your guide will lead you through the gates of the old city where you will discover the ancient streets and neighborhoods, visit the various artisan sections (including the tanneries), and see the important historic monuments (including the tomb of Idriss II and the Al-Qarawaiyin University).", image: "images/highlights_day4.jpeg" },
            { day: "Day 5", title: "Fes to Merzouga", desc: "After breakfast, you will depart from Fes and head to the desert. Your first stop on the way will be the interesting, Alpine-like city of Ifraine. After a quick stop here for coffee and a snack, you’ll continue into the Middle Atlas Mountains and through the largest cedar forest in Africa which is also home to the Barbary macaques (aka Atlas monkeys) which are sure to entertain. After you’ve crossed through the Middle Atlas Mountains, you’ll pass through the city of Midelt located on the high plains between the Middle and High Atlas Mountains and then continue through the High Atlas Mountains via the Ziz River Gorge. After passing through the High Atlas Mountains, you will enter the desert region and the lush oasis of Erfoud. From here, you’ll make the final leg of the journey to the Merzouga, a small city located on the edge of the big dunes of Erg Chebbi. Upon your arrival, you will check into your guest house and relax from your full day’s journey.", image: "images/highlights_day5.jpeg" },
            { day: "Day 6", title: "Merzouga to Dades Valley", desc: "This morning, you’ll want to be sure to get up early to watch the sun rise over the dunes (don’t forget to set your alarm). Grab some coffee and climb the nearest dune and watch as the sun lights the sand aflame. After this near-transcendental experience, you’ll have breakfast at camp and prepare for your day. When you are ready, you’ll take a 4×4 transfer back to the edge of the dunes. Once you reunite with your tour manager, you’ll make your way to Dades Valley. Your first stop, today, will be to visit the ancient irrigation system that once brought water to the desert from the distant Saghro Mountains. From here, you’ll head to the oasis town of Tinghir where you will have a guided walk of the palmeraie and Mellah (old Jewish area). Next, you’ll visit nearby Todgha Gorge where you will walk through the most impressive part of the canyon. After this, you’ll head to your accommodations located in the Dades Valley where you will enjoy dinner at your hotel.", image: "images/highlights_day6.jpeg" },
            { day: "Day 7", title: "Valley of Roses", desc: "Today is all about exploring how the locals live in this magical place where time seems to run slow and fast simultaneously. After a leisurely breakfast, you’ll head to the “next valley over” in the heart of the Rose Valley. On the way, you can visit a local market and then go to the home of a local family where you can help to prepare lunch (or just relax) and then join the family for a traditional couscous lunch. After lunch (and a little relaxation), you can explore a little more of the Valley either by car or by foot before heading back to your hotel in time for dinner. This area also has tons of great hiking, so if you prefer a more active day, you can choose from several options from a short hike in the unique rock formation known as the Monkey Fingers to a full-day hike through the Dades Canyon or over the mountain to the M’Goun River valley.", image: "images/highlights_day7.jpeg" },
            { day: "Day 8", title: "Dades to Marrakech", desc: "After breakfast this morning, you and your driver will begin the journey to Marrakech by following the Road of a Thousand Kasbahs through the heart of the Valley of Roses to Ouarzazate, the Hollywood of Morocco. If you are interested and time permits, you can have a backlot tour of one of the active film studios here before making the short drive to the UNESCO World Heritage site of Ait Ben Haddou. If this impressive ksar looks familiar, it may be because it starred (or at least served as a backdrop) for many films and TV shows such as Gladiator, Jewel of the Nile, Lawrence of Arabia, and Game of Thrones. Upon your arrival here, you’ll stop first for a panoramic view of this “mud city” and then head in for a closer look. After your visit here, the adventure will continue as you cross over the High Atlas Mountains via the Tizi n’Tichka pass, reaching an altitude of nearly 7500 feet above sea level before beginning your descent to Marrakech. You will arrive to your accommodations in Marrakech by late afternoon.", image: "images/highlights_day8.jpeg" },
            { day: "Day 9", title: "Marrakech Immersion", desc: "After breakfast, your local city guide will meet you at your riad and show you all around Marrakech. Your tour will include visits to some important monuments of the Red City such as Bahia Palace, Ben Yousef Madrassa, and/or Koutoubia Mosque. In between these sites, you’ll explore the various artisanal sections of the souks where people have practiced their crafts for centuries. Your tour will end around lunchtime, and then you will have the rest of the day free to explore on your own. Don’t forget to make your way to Jemaa el F’na in the late afternoon to one of the cafés overlooking the square to watch it come alive as the sun goes down!", image: "images/highlights_day9.jpeg" },
            { day: "Day 10", title: "Au Revoir", desc: "This morning, after breakfast, you will transfer to the airport of your choice (Marrakech or Casablanca). There your tour manager will bid you a fond au revoir until you next trip to Morocco!", image: "images/highlights_day10.jpeg" }
        ]
    },

    // --- 6. South of Morocco Private Immersion (8 Days) ---
    {
        id: 6,
        title: "South of Morocco Private Immersion",
        price: "On Request",
        duration: "8 Days",
        location: "Marrakech ⇄ Sahara",
        image: "/images/6.jpeg",
        desc: "This 8-day Morocco tour blends culture, nature, and adventure. Starting in Marrakech, you’ll explore historic sites and bustling souks before crossing the Atlas Mountains to Ouarzazate and the scenic Dades Valley. Highlights include Todgha Gorge, a camel trek into the Sahara, and a night in a luxury desert camp.",
        highlights: ["Marrakech", "Dades Valley", "Sahara Desert", "Ait Ben Haddou"],
        itinerary: [
            { day: "Day 1", title: "Welcome to Morocco", desc: "Upon your arrival at the airport, your personal driver will greet you and transfer you to your riad in Marrakech for the night, where you will have an opportunity to rest and recuperate from your travels. Depending on your time of arrival, you may wish to explore a little and your driver will be at your disposal should you need him.", image: "images/south_day1.jpeg" },
            { day: "Day 2", title: "Marrakech Immersion", desc: "After breakfast, your local city guide will meet you at your riad and show you all around Marrakech. Your tour will include visits to some important monuments of the Red City such as Bahia Palace, Ben Yousef Madrassa, and/or Koutoubia Mosque. In between these sites, you’ll explore the various artisanal sections of the souks where people have practiced their crafts for centuries. Your tour will end around lunchtime, and then you will have the rest of the day free to explore on your own.", image: "images/south_day2.jpeg" },
            { day: "Day 3", title: "Marrakech to Dades Valley", desc: "After breakfast this morning, you and your driver will depart from your riad in Marrakech to begin your odyssey to the Sahara Desert. Your day will start with crossing over the High Atlas Mountains via the Tizi n’Tichka Pass, reaching an altitude of nearly 7500 feet above sea level. They say that life is about the journey and not the destination and this is certainly true when you are on this road. Upon your arrival to the city known both as the “Door of the Desert” and the “Hollywood of Morocco”, you will visit the former palace of the Glaoui clan, Kasbah Taourirt OR, if you are a movie buff, you may enjoy a backlot tour of one of the active film studios. After your visit here, you will take the Road of a Thousand Kasbahs through the Valley of Roses and into the breathtaking Dades Valley where you will stop for the night.", image: "images/south_day3.jpeg" },
            { day: "Day 4", title: "Dades to Merzouga", desc: "After breakfast, you will depart your accommodations in Dades and continue your journey towards the dunes of Merzouga. Today’s first stop will be the oasis city of Tinghir. You’ll enjoy a guided walk in the palmeraie here before transferring to nearby Todgha Gorge where you will have an opportunity to walk through the most impressive part of the canyon. In this narrow section of the gorge (as little as 33 feet wide), the rock walls climb straight up 525 feet on either side. From here, you will complete the final leg of the journey to the big dunes of Erg Chebbi near Merzouga. Tonight, you will stay at a guest house on the edge of the dunes. Upon your arrival, you’ll have a chance to rest and relax before dinner is served.", image: "images/south_day4.jpeg" },
            { day: "Day 5", title: "Desert Tour & Camel Trek", desc: "Today you will enjoy a tour of the desert region. Your first stop of the day will be to visit the village of Khamlia which is inhabited by Gnaoua musicians. After this visit, you will head to the nearby city of Rissani. On market days this sleepy city is transformed into a bustling metropolis where people from all over the region come to buy and sell their produce, livestock, and wares. After this, you’ll head to Erfoud to visit a small museum with an impressive collection of fossils found in Morocco. When you have finished your tour of the area, you will head to the edge of the dunes where you will transfer to your next mode of transportation, a camel. You will begin your camel trek into the dunes to your luxury Berber camp for the night. Dinner will be served at camp followed by traditional music.", image: "images/south_day5.jpeg" },
            { day: "Day 6", title: "Merzouga to Agdz", desc: "This morning, you’ll want to wake up early to watch the sand change colors as the sun comes up (be sure to set your alarm!). Grab a cup of coffee and climb up the nearest dune to watch this spectacular show. After this nearly transcendental experience, you will have breakfast at camp and time to prepare for your day. When you are ready, you’ll take to your camels once again to the edge of the dunes where you will meet your tour manager and transfer back to a more conventional mode of transportation. Once you reunite with your driver, you’ll bid the desert region au revoir and make your way into the Draa Valley of Morocco. This fertile river valley located in the Saghro (or Black) Mountain range is known as the Valley of a Million Palms and it is easy to see why. Here you will come upon Kasbah Tamnougalt, another important stop along the old salt caravan route. You’ll have a guided visit of the Kasbah and the adjacent gardens.", image: "images/south_day6.jpeg" },
            { day: "Day 7", title: "Agdz to Marrakech via Ait Ben Haddou", desc: "After breakfast, today, you will begin the final leg of your journey back to Marrakech. You’ll continue along the Draa Valley until you once again reach Ouarzazate. From here it is just a short drive to the UNESCO World Heritage Site of Ait Ben Haddou. If this impressive ksar looks familiar, it may be because it starred (or at least served as a backdrop) for many films and TV shows such as Gladiator, Jewel of the Nile, Lawrence of Arabia, and Game of Thrones. Upon your arrival here, you’ll stop first for a panoramic view of this “mud city” and then head in for a closer look. You’ll cross the riverbed to the entrance and then climb the steep and winding streets to the granary, or “bank” at the top for amazing panoramic views of the whole region. After admiring the impressive views, you’ll make your way back down to your vehicle and travel once more over the High Atlas Mountains via the Tizi n’ Tichka pass reaching Marrakech by the early evening.", image: "images/south_day7.jpeg" },
            { day: "Day 8", title: "Bon Voyage", desc: "This morning after breakfast, you will transfer to the Marrakech Menara Airport in plenty of time for your departing flight.", image: "images/south_day8.jpeg" }
        ]
    },

    // --- 7. North to South of Morocco Private Tour (8 Days) ---
    {
        id: 7,
        title: "North to South of Morocco Private Tour",
        price: "On Request",
        duration: "8 Days",
        location: "Tangier -> Marrakech",
        image: "/images/7.jpeg",
        desc: "This 8-day Morocco tour begins in the vibrant northern port city of Tangier and winds through the Blue City of Chefchaouen, the ancient ruins of Volubilis, and the imperial cities of Meknes and Fes. You’ll journey through mountain forests and Alpine villages, cross the Atlas Mountains, and trek by camel into the Sahara for a magical night under the stars.",
        highlights: ["Chefchaouen", "Fes", "Sahara", "Marrakech"],
        itinerary: [
            { day: "Day 1", title: "Welcome to Morocco", desc: "Welcome to Morocco! Your tour manager will be awaiting your arrival at the airport (or ferry port) in Tangier. Once you have made your introductions, you will head inland to the magical Blue City of Chefchaouen nestled between two peaks in the Rif Mountains. Once here, you will check into your accommodations and the re-join your tour manager for an orientation walk in the city. After you’ve gotten your bearings, you’ll be free to explore on your own. Be sure to hike to the Spanish Mosque (ask your tour manager for directions or just follow the people) in the late afternoon to watch the sun set over the city.", image: "images/northsouth_day1.jpeg" },
            { day: "Day 2", title: "Chefchaouen to Fes", desc: "After breakfast today, you’ll say farewell to Chefchaouen and begin your journey to Fes, the first imperial city of Morocco and the spiritual capital of the country. On the way, you will stop to visit the ruins of the Roman outpost of Volubilis. Before the Romans came, Volubilis was an Amazigh city known as Oulili which dates back to the 3rd century B.C. After a guided tour of Volubilis, you’ll head to the lessor known imperial city of Meknes. Note: Most of the monuments in Meknes are currently undergoing extensive restoration and are closed for the foreseeable future. You may choose to skip this stop to have more time in Chefchaouen or Fes, if you wish.", image: "images/northsouth_day2.jpeg" },
            { day: "Day 3", title: "Fes Immersion", desc: "Today after breakfast, your local guide will meet you at your riad and together you will embark on an odyssey through this medieval city. You will begin your tour with your driver as you make your way to the Royal Palace. After this, you will walk through the old Mellah (Jewish Quartier) where you will note a change in the architecture. When you’ve finished here, you will head to one of the towers (or Borj) of the wall that surrounds the city for panoramic views of the whole medina. Next, you’ll head to a mosaic house where you will have a demonstration of the traditional pottery methods utilized by Fassi artisans. From here, your guide will lead you through the gates of the old city where you will discover the ancient streets and neighborhoods, visit the various artisan sections (including the tanneries), and see the important historic monuments (including the tomb of Idriss II and the Al-Qarawaiyin University).", image: "images/northsouth_day3.jpeg" },
            { day: "Day 4", title: "Fes to Merzouga", desc: "After breakfast, you will depart from Fes and head to the desert. Your first stop on the way will be the interesting, Alpine-like city of Ifraine. Driving through this city, you will think that you have been teleported to Switzerland. After a quick stop here for coffee and a snack, you’ll continue into the Middle Atlas Mountains and through the largest cedar forest in Africa which is also home to the Barbary macaques (aka Atlas monkeys). After you’ve crossed through the Middle Atlas Mountains, you’ll pass through the city of Midelt and then continue through the High Atlas Mountains via the Ziz River Gorge. After passing through the High Atlas Mountains, you will enter the desert region and the lush oasis of Erfoud. From here, you’ll make the final leg of the journey to the Merzouga, a small city located on the edge of the big dunes of Erg Chebbi. Upon your arrival, you will check into your guest house and relax from your full day’s journey.", image: "images/northsouth_day4.jpeg" },
            { day: "Day 5", title: "Merzouga to Dades Valley", desc: "This morning, you’ll want to be sure to get up early to watch the sun rise over the dunes (don’t forget to set your alarm!). Grab some coffee and climb the nearest dune and watch as the sun lights the sand aflame. After this near-transcendental experience, you’ll have breakfast at camp and prepare for your day. When you are ready, you’ll take a 4×4 transfer back to the edge of the dunes. Once you reunite with your tour manager, you’ll make your way to Dades Valley. Your first stop, today, will be to visit the ancient irrigation system that once brought water to the desert from the distant Saghro Mountains. From here, you’ll head to the oasis town of Tinghir where you will have a guided walk of the palmeraie and Mellah (old Jewish area). Next, you’ll visit nearby Todgha Gorge where you will walk through the most impressive part of the canyon. After this, you’ll head to your accommodations located in the Dades Valley where you will enjoy dinner at your hotel.", image: "images/northsouth_day5.jpeg" },
            { day: "Day 6", title: "Dades to Marrakech", desc: "After breakfast this morning, you and your driver will begin the journey to Marrakech by following the Road of a Thousand Kasbahs through the heart of the Valley of Roses to Ouarzazate, the Hollywood of Morocco. If you are interested and time permits, you can have a backlot tour of one of the active film studios here before making the short drive to the UNESCO World Heritage site of Ait Ben Haddou. If this impressive ksar looks familiar, it may be because it starred (or at least served as a backdrop) for many films and TV shows such as Gladiator, Jewel of the Nile, Lawrence of Arabia, and Game of Thrones. Upon your arrival here, you’ll stop first for a panoramic view of this “mud city” and then head in for a closer look. After your visit here, the adventure will continue as you cross over the High Atlas Mountains via the Tizi n’Tichka pass, reaching an altitude of nearly 7500 feet above sea level before beginning your descent to Marrakech. You will arrive to your accommodations in Marrakech by late afternoon.", image: "images/northsouth_day6.jpeg" },
            { day: "Day 7", title: "Marrakech Immersion", desc: "After breakfast, your local city guide will meet you at your riad and show you all around Marrakech. Your tour will include visits to some important monuments of the Red City such as Bahia Palace, Ben Yousef Madrassa, and/or Koutoubia Mosque. In between these sites, you’ll explore the various artisanal sections of the souks where people have practiced their crafts for centuries. Your tour will end around lunchtime, and then you will have the rest of the day free to explore on your own. Don’t forget to make your way to Jemaa el F’na in the late afternoon to one of the cafés overlooking the square to watch it come alive as the sun goes down!", image: "images/northsouth_day7.jpeg" },
            { day: "Day 8", title: "Au Revoir", desc: "This morning, after breakfast, you will transfer to the airport of your choice (Marrakech or Casablanca). There your tour manager will bid you a fond au revoir until you next trip to Morocco!", image: "images/northsouth_day8.jpeg" }
        ]
    },

    // --- 8. Camel Trek Private Tour from Marrakech (4 Days) ---
    {
        id: 8,
        title: "Camel Trek Private Tour from Marrakech",
        price: "On Request",
        duration: "4 Days",
        location: "Marrakech ⇄ Sahara",
        image: "/images/8.jpeg",
        desc: "A quick but immersive escape to the desert. Experience the High Atlas Mountains, the Dades Valley, and a magical camel trek into the dunes of Merzouga for a night under the stars.",
        highlights: ["High Atlas", "Dades Valley", "Camel Trek", "Merzouga"],
        itinerary: [
            { day: "Day 1", title: "Marrakech to Dades Valley", desc: "After breakfast this morning, you and your driver will depart from your riad in Marrakech to begin your odyssey to the Sahara Desert. Your day will start with crossing over the High Atlas Mountains via the Tizi n’Tichka Pass, reaching an altitude of nearly 7500 feet above sea level. They say that life is about the journey and not the destination and this is certainly true when you are on this road. There will be plenty of stops for tea and photographs as you take in the breathtaking vistas before arriving in Ouarzazate. Upon your arrival to the city known both as the “Door of the Desert” and the “Hollywood of Morocco”, you will visit the former palace of the Glaoui clan, Kasbah Taourirt, OR, if you are a movie buff, you may enjoy a backlot tour of one of the active film studios here. After your visit, you will take the Road of a Thousand Kasbahs through the Valley of Roses and into the breathtaking Dades Valley where you will stop for the night.", image: "images/camel_day1.jpeg" },
            { day: "Day 2", title: "Dades to Merzouga", desc: "After breakfast, you will depart your accommodations in Dades and continue your journey towards the dunes of Merzouga. Your first stop of today will be the oasis city of Tinghir. You’ll enjoy a guided walk in the palmeraie here before transferring to nearby Todgha Gorge where you will have an opportunity to walk through the most impressive part of the canyon. In this narrow section of the gorge (as little as 33 feet wide), the rock walls climb straight up 525 feet on either side. After you’ve stretched your legs, you will continue your journey into the desert region where you will have a chance to search for fossils in the wild and visit a small fossil museum with an impressive collection of specimens found in Morocco. From here, you will complete the final leg of the journey to the big dunes of Erg Chebbi near Merzouga. When you reach the edge of the dunes, you will transfer to your next mode of transportation, a camel, and begin your trek into the dunes to your luxury Berber camp for the night. Dinner will be served at camp followed by traditional music.", image: "images/camel_day2.jpeg" },
            { day: "Day 3", title: "Merzouga to Agdz", desc: "This morning, you’ll want to wake up early to watch the sand change colors as the sun comes up (be sure to set your alarm!). Grab a cup of coffee and climb up the nearest dune to watch this spectacular show. After this nearly transcendental experience, you will have breakfast at camp and time to prepare for your day. When you are ready, you’ll take to your camels once again to the edge of the dunes where you will meet your tour manager and transfer back to a more conventional mode of transportation. Before you leave the desert region, you’ll have a little more time to explore the area. You can stop to visit the village of Khamlia which is inhabited by Gnaoua musicians. After this visit, you can head to the nearby city of Rissani. When you have completed your visit here, you’ll bid the desert region au revoir and make your way into the Draa Valley of Morocco. This fertile river valley located in the Saghro (or Black) Mountain range is known as the Valley of a Million Palms and it is easy to see why. Here, you will come upon Kasbah Tamnougalt, another important stop along the old salt caravan route. You’ll have a guided visit of the Kasbah and the adjacent gardens.", image: "images/camel_day3.jpeg" },
            { day: "Day 4", title: "Agdz to Marrakech", desc: "After breakfast, today, you will begin the final leg of your journey back to Marrakech. You’ll continue along the Draa Valley until you once again reach Ouarzazate. From here it is just a short drive to the UNESCO World Heritage Site of Ait Ben Haddou. If this impressive ksar looks familiar, it may be because it starred (or at least served as a backdrop) for many films and TV shows such as Gladiator, Jewel of the Nile, Lawrence of Arabia, and Game of Thrones. Upon your arrival here, you’ll stop first for a panoramic view of this “mud city” and then head in for a closer look. You’ll cross the riverbed to the entrance and then climb the steep and winding streets to the granary, or “bank” at the top for amazing panoramic views of the whole region. After admiring the impressive views, you’ll make your way back down to your vehicle and travel once more over the High Atlas Mountains via the Tizi n’ Tichka pass reaching Marrakech by the early evening. Your tour manager will drop you off at your accommodations in Marrakech and, once you are safely delivered, will bid you au revoir until your next trip to Morocco.", image: "images/camel_day4.jpeg" }
        ]
    }
];